### ISSUE TITLE
Error Create Group

### ISSUE THREAD

**Issue by alam-haha** [manufino/AutoCAD#1]
I am trying to create a group, consists of a single line.

I have Copy and Paste from the example, but the program is error.

here is my program

```
# Create the AutoCAD object
acad = AutoCAD()

# Define start and end points using APoint
start_point = APoint(0, 0, 0)
end_point = APoint(100, 100, 0)

# Draw the line
line = acad.add_line(start_point, end_point)

group = acad.create_group("MyGroup", line)
```

and this is the error

> AutoCADError: Error creating group 'MyGroup': This object does not support enumeration
> Traceback (most recent call last):
>   File "D:\Programming Project\Python\Python Autocad\Coba-coba\Manufino Library\ManufinoLib.py", line 530, in create_group
>     for obj in objects:
>   File "D:\Programming Project\Python\Python Autocad\Coba-coba\venv\lib\site-packages\win32com\client\dynamic.py", line 329, in __getitem__
>     raise TypeError("This object does not support enumeration")
> TypeError: This object does not support enumeration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Programming Project\Python\Python Autocad\Coba-coba\Manufino Library\try_manufinolib.py", line 14, in <module>
>     group = acad.create_group("MyGroup", line)
>   File "D:\Programming Project\Python\Python Autocad\Coba-coba\Manufino Library\ManufinoLib.py", line 534, in create_group
>     raise AutoCADError(f"Error creating group '{group_name}': {e}")
> ManufinoLib.AutoCADError: Error creating group 'MyGroup': This object does not support enumeration

**Comment by Jones-peter** [comment]
use 

```python
# Create the AutoCAD object
acad = AutoCAD()

# Define start and end points using APoint
start_point = APoint(0, 0, 0)
end_point = APoint(100, 100, 0)

# Draw the line
line = acad.add_line(start_point, end_point)
time.sleep(2)
group = acad.create_group("MyGroup", line)

```
because your autocad application is responding slow that's why this error occurred

**Comment by manufino** [comment]
I fixed it with the latest commit.

The create_group method was raising a COM error:
`'Invalid object array' (Serie di oggetti non valida)
`
when calling group.AppendItems([obj]). This happened because Python lists are not automatically translated into the SAFEARRAY of IDispatch objects required by AutoCAD's COM interface.

We now explicitly wrap the list of AutoCAD objects using win32com.client.VARIANT with pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH. This ensures the COM method receives the array in the expected format.

Code fix:
`variant_array = win32com.client.VARIANT(
    pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH,
    objects
)
group.AppendItems(variant_array)
`
This change makes the create_group method robust and fully compatible with AutoCAD's COM API, avoiding enumeration and type errors when passing entities.
